#!/bin/sh
sleep 2
volumeicon &
#compton &
nm-applet &
feh --randomize --bg-fill ~/Pictures/*
dbus-update-activation-environment --systemd --all
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
dunst
